name: YOUR_PROJECT_NAME
channels:
  - conda-forge
  - gurobi
  - nodefaults # never remove this!
dependencies:
  - python=3.11
  - pandas=2.2
  - pyscipopt=5.1
  - scip=9.1
  - bs4=4.13
  - lxml=5.4
  - gurobi=12.0
  - matplotlib=3.10
  - scipy=1.16