[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "alpaca"
version = "0.1.0"
description = "ALPACA – Optimization tools for OSIL / SCIP-based models"
readme = "README.md"
requires-python = ">=3.11,<3.13"
license = { text = "MIT" }

authors = [
  { name = "Tobias Kuen" },
  { name = "Robert Burlacu" }
]

dependencies = [
  "pandas>=2.2,<2.3",
  "beautifulsoup4>=4.13,<4.14",
  "lxml>=5.4,<5.5",
  "matplotlib>=3.10,<3.11",
  "scipy>=1.16,<1.17",
  "scikit-learn>=1.8,<1.9",
  "gurobipy>=12.0,<12.1",
  "grblogtools>=2.2,<2.3",
  "pyscipopt>=5.1,<5.2"
]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["test"]
