# -*- coding: utf-8 -*-
"""
@authors: kuen,
"""
from __future__ import annotations
from typing import TYPE_CHECKING

from alpaca.utils.logger import logger
from alpaca.pwl import multiple_choice_method as mcm, delta_method as dem
import alpaca.expressions.one_dim_expression as ode
import alpaca.model_data.constraint as con
from alpaca.utils.localized_string_factory import LocalizedStringFactory as lsf
import alpaca.settings as s

if TYPE_CHECKING:
    from alpaca.model_data.model_data import ModelData


class PWLHandler:
    """
    Manages the application of Piecewise Linear (PWL) relaxations to various
    expressions within a model.

    This class is responsible for discretizing variable domains, and applying the appropriate
    relaxation methods based on the model's settings.
    """

    def __init__(self, model_data: ModelData):
        self.model_data = model_data

    def apply_relaxations(self):
        """
        Orchestrates the entire PWL relaxation process.

        This is the main public method that executes the sequence of steps required
        to apply all necessary PWL relaxations. It calls the specific methods
        for domain discretization and relaxation of one-dimensional and multilinear expressions.
        """
        logger.info(lsf.info_create_piecewise_linear_relaxation())
        self._discretize_variable_domains()
        self._apply_piecewise_linear_relaxation_for_one_dim_expressions()
        self._apply_piecewise_constant_relaxation_for_multilinear_expressions()

    def _discretize_variable_domains(self) -> None:
        """
        Identifies and discretizes the domains of relevant variables.

        This method iterates through all variables in the model. For each
        non-binary variable marked for discretization, it creates a PWL
        representation using either the Multiple Choice Method or the Delta
        Method, based on the model's settings. The new binary variables,
        continuous variables, and constraints generated by the PWL method are
        then collected and added to the model data.
        """
        pwl_variables = []
        pwl_constraints = []
        for variable in self.model_data.variables.values():
            if variable.is_discretized and variable.var_type != lsf.var_type_binary():
                variable.pwl = (
                    mcm.MultipleChoiceMethod(variable)
                    if self.model_data.settings.pwl_method
                    == lsf.pwl_method_multiple_choice()
                    else dem.DeltaMethod(variable)
                )
                pwl_variables.extend(
                    variable.pwl.pwl_variables_binary
                    + variable.pwl.pwl_variables_continuous
                )
                pwl_constraints.extend(variable.pwl.pwl_constraints)
        for variable in pwl_variables:
            self.model_data.add_variable(variable)
        for constraint in pwl_constraints:
            self.model_data.add_constraint(constraint)

    def _apply_piecewise_linear_relaxation_for_one_dim_expressions(self) -> None:
        """
        Applies piecewise linear relaxation to all one-dimensional expressions.

        It iterates through each one-dimensional expression in the model.
        - For `AbsExpression`, it calls a dedicated handler.
        - For other expressions, it uses the variable's PWL representation
          (created during domain discretization) to generate constraints that
          couple the variable's partitioned domain to the function's value,
          effectively creating the PWL approximation. These new constraints
          are then added to the model.
        """
        for expression in self.model_data.expressions.one_dim_expressions.values():
            if isinstance(expression, ode.AbsExpression):
                expression.handle_abs_expression(self.model_data)
                continue
            if not expression.variable.is_discretized:  # ub = lb
                assert abs(
                    expression.variable.ub - expression.variable.lb
                ) < s.StaticSettings.feasibility_tolerance
                self.model_data.add_constraint(
                    con.LinearConstraint(
                        lsf.con_name_pwl_delta_approximation(expression.name),
                        con_type=lsf.constraint_eq(),
                        variables=[(1.0, expression.representative_variable)],
                        rhs=expression.f(expression.variable.lb),
                    )
                )
                continue
            constraints = (
                expression.variable.pwl.couple_domain_to_function_value_one_dim(
                    expression, approximation=self.model_data.settings.approximation
                )
            )
            for constraint in constraints:
                self.model_data.add_constraint(constraint)

    def _apply_piecewise_constant_relaxation_for_multilinear_expressions(
        self,
    ) -> None:
        """
        Applies piecewise constant relaxation to bilinear and multilinear expressions.

        This relaxation is applied based on specific model settings:
        - It handles bilinear expressions if the 'bilinear_handling' setting is 2.
        - It handles multilinear expressions if they are not configured to be
          reformulated into bilinear expressions.

        For each eligible expression, it uses the PWL representation of its
        representative variable to generate and add the necessary constraints
        for the piecewise constant relaxation.
        """
        if self.model_data.settings.bilinear_handling == 2:
            for expression in self.model_data.expressions.bilinear_expressions.values():
                if not expression.representative_variable.is_discretized:  # ub = lb
                    assert (
                        expression.representative_variable.ub
                        == expression.representative_variable.lb
                    )
                    continue
                constraints = (
                    expression.representative_variable.pwl.apply_pwc_relaxation(
                        expression,
                        approximation=self.model_data.settings.approximation,
                    )
                )
                for constraint in constraints:
                    self.model_data.add_constraint(constraint)
        if not self.model_data.settings.reformulate_multilinear_to_bilinear:
            for (
                expression
            ) in self.model_data.expressions.multilinear_expressions.values():
                constraints = (
                    expression.representative_variable.pwl.apply_pwc_relaxation(
                        expression,
                        approximation=self.model_data.settings.approximation,
                    )
                )
                for constraint in constraints:
                    self.model_data.add_constraint(constraint)
